nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: "${GITHUB_TOKEN}"

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${FONTAWESOME_NPM_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com/"
  upfluence:
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
