import Ember from 'ember';

export default Ember.Route.extend({
  model: function() {
    return [
      {
        "id": 528,
        "supplier_interest": "interested",
        "selectability": "good",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": true,
        "price": '490.0 EUR',
        "proposed_price": '490.0 EUR',
        "comment": "Cat\u00e9gorie Finance - Education Top 20% ",
        "visible_by_client": true,
      },
      {
        "id": 531,
        "supplier_interest": "interested",
        "selectability": "great",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": true,
        "price": '590.0 EUR',
        "proposed_price": '590.0 EUR',
        "proposed_price_currency": "EUR",
        "comment": "Tr\u00e8s bonne visibilit\u00e9 - bonne audience Top 5%",
        "visible_by_client": true,
      },
      {
        "id": 541,
        "supplier_interest": "interested",
        "selectability": "great",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": true,
        "price": '540.0 EUR',
        "proposed_price": '540.0 EUR',
        "comment": "Bonne cible B2B - conseils professionnels Top 1%",
        "visible_by_client": true,
      },
      {
        "id": 523,
        "supplier_interest": "interested",
        "selectability": "good",
        "client_approved_for_drafting": true,
        "admin_approved_for_drafting": false,
        "price": '300.0 EUR',
        "proposed_price": '300.0 EUR',
        "comment": "Entrepreneuriat - business Top 20%",
        "visible_by_client": true,
      },
      {
        "id": 524,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "proposed_price": 0.0,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 525,
        "supplier_interest": "interested",
        "selectability": "good",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": '200.0 EUR',
        "proposed_price": '200.0 EUR',
        "comment": "Entrepreneuriat - business Top 20%",
        "visible_by_client": false,
      },
      {
        "id": 526,
        "supplier_interest": "interested",
        "selectability": "great",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": '207.0 EUR',
        "proposed_price": '248.4 EUR',
        "proposed_price_currency": "EUR",
        "comment": "Top 5% - blog reconnu en accord avec la cible recherch\u00e9e",
        "visible_by_client": false,
      },
      {
        "id": 527,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "proposed_price": 0.0,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 530,
        "supplier_interest": "interested",
        "selectability": "good",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": '420.0 EUR',
        "proposed_price": '420.0 EUR',
        "comment": "Power Middle - sujets B2B ",
        "visible_by_client": false,
      },
      {
        "id": 532,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "proposed_price": 0.0,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 535,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "proposed_price": 0.0,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 536,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "proposed_price": 0.0,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 542,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "proposed_price": 0.0,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 545,
        "supplier_interest": "interested",
        "selectability": "good",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": '700.0 EUR',
        "proposed_price": '1000.0 EUR',
        "comment": "Sujet tr\u00e8s orient\u00e9 RH - ligne \u00e9ditoriale correspondante \u00e0 la cible Top 20%",
        "visible_by_client": false,
      },
      {
        "id": 547,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "proposed_price": 0.0,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 546,
        "supplier_interest": "interested",
        "selectability": "good",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": true,
        "price": '450.0 EUR',
        "proposed_price": '450.0 EUR',
        "comment": "Ax\u00e9 entrepreneuriat - formation - jeunes dipl\u00f4m\u00e9s",
        "visible_by_client": true,
      },
      {
        "id": 544,
        "supplier_interest": "interested",
        "selectability": "great",
        "client_approved_for_drafting": true,
        "admin_approved_for_drafting": true,
        "price": '60.0 EUR',
        "proposed_price": '60.0 EUR',
        "comment": "Tr\u00e8s orient\u00e9 B2B - Correspond r\u00e9ellement \u00e0 la cible - Top 20%",
        "visible_by_client": true,
      },
      {
        "id": 553,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "proposed_price": 0.0,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 554,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "proposed_price": 0.0,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 557,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 560,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 561,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 562,
        "supplier_interest": "interested",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": "EUR",
        "proposed_price": 0.0,
        "proposed_price_currency": "EUR",
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 567,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 571,
        "supplier_interest": "not_interested",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": "USD",
        "proposed_price": 0.0,
        "proposed_price_currency": "USD",
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 573,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "proposed_price": 0.0,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 522,
        "supplier_interest": "interested",
        "selectability": "great",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": true,
        "price": '560.0 EUR',
        "proposed_price": '560.0 EUR',
        "comment": "Top 1% - B2B - tr\u00e8s bonne visibilit\u00e9",
        "visible_by_client": true,
      },
      {
        "id": 577,
        "supplier_interest": "not_interested",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": '0.0 USD',
        "proposed_price": '0.0 USD',
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 578,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "proposed_price": 0.0,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 579,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": '0.0 USD',
        "proposed_price": '0.0 USD',
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 583,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "proposed_price": 0.0,
        "comment": null,
        "visible_by_client": false,
      }
    ];
  },
});
