import Ember from 'ember';

export default Ember.Route.extend({
  model: function() {
    return [
      {
        "id": 528,
        "supplier_interest": "interested",
        "selectability": "good",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": true,
        "price": 490.0,
        "price_currency": "EUR",
        "proposed_price": 490.0,
        "proposed_price_currency": "EUR",
        "comment": "Cat\u00e9gorie Finance - Education Top 20% ",
        "visible_by_client": true,
      },
      {
        "id": 531,
        "supplier_interest": "interested",
        "selectability": "great",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": true,
        "price": 590.0,
        "price_currency": "EUR",
        "proposed_price": 590.0,
        "proposed_price_currency": "EUR",
        "comment": "Tr\u00e8s bonne visibilit\u00e9 - bonne audience Top 5%",
        "visible_by_client": true,
      },
      {
        "id": 541,
        "supplier_interest": "interested",
        "selectability": "great",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": true,
        "price": 540.0,
        "price_currency": "EUR",
        "proposed_price": 540.0,
        "proposed_price_currency": "EUR",
        "comment": "Bonne cible B2B - conseils professionnels Top 1%",
        "visible_by_client": true,
      },
      {
        "id": 523,
        "supplier_interest": "interested",
        "selectability": "good",
        "client_approved_for_drafting": true,
        "admin_approved_for_drafting": false,
        "price": 300.0,
        "price_currency": "EUR",
        "proposed_price": 300.0,
        "proposed_price_currency": "EUR",
        "comment": "Entrepreneuriat - business Top 20%",
        "visible_by_client": true,
      },
      {
        "id": 524,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 525,
        "supplier_interest": "interested",
        "selectability": "good",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 200.0,
        "price_currency": "EUR",
        "proposed_price": 200.0,
        "proposed_price_currency": "EUR",
        "comment": "Entrepreneuriat - business Top 20%",
        "created_at": "2017-01-16T13:50:15.977Z",
        "updated_at": "2017-01-20T14:23:47.763Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-525",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": false,
        "campaign_id": 5,
        "supplier_id": 523,
        "draft_ids": [],
        "link_ids": [],
        "latest_draft_id": null,
        "payment_request_id": null
      },
      {
        "id": 526,
        "supplier_interest": "interested",
        "selectability": "great",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 207.0,
        "price_currency": "EUR",
        "proposed_price": 248.4,
        "proposed_price_currency": "EUR",
        "comment": "Top 5% - blog reconnu en accord avec la cible recherch\u00e9e",
        "created_at": "2017-01-16T13:50:16.334Z",
        "updated_at": "2017-01-24T10:21:43.929Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-526",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": false,
        "campaign_id": 5,
        "supplier_id": 524,
        "draft_ids": [],
        "link_ids": [],
        "latest_draft_id": null,
        "payment_request_id": null
      },
      {
        "id": 527,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "created_at": "2017-01-16T13:50:16.411Z",
        "updated_at": "2017-01-16T13:50:16.411Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-527",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": false,
        "campaign_id": 5,
        "supplier_id": 525,
        "draft_ids": [],
        "link_ids": [],
        "latest_draft_id": null,
        "payment_request_id": null
      },
      {
        "id": 530,
        "supplier_interest": "interested",
        "selectability": "good",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 420.0,
        "price_currency": "EUR",
        "proposed_price": 420.0,
        "proposed_price_currency": "EUR",
        "comment": "Power Middle - sujets B2B ",
        "created_at": "2017-01-16T13:50:16.478Z",
        "updated_at": "2017-01-20T14:47:38.883Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-530",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": false,
        "campaign_id": 5,
        "supplier_id": 528,
        "draft_ids": [],
        "link_ids": [],
        "latest_draft_id": null,
        "payment_request_id": null
      },
      {
        "id": 532,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "created_at": "2017-01-16T13:50:16.673Z",
        "updated_at": "2017-01-16T13:50:16.673Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-532",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": false,
        "campaign_id": 5,
        "supplier_id": 530,
        "draft_ids": [],
        "link_ids": [],
        "latest_draft_id": null,
        "payment_request_id": null
      },
      {
        "id": 535,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "created_at": "2017-01-16T13:50:16.773Z",
        "updated_at": "2017-01-16T13:50:16.773Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-535",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": false,
        "campaign_id": 5,
        "supplier_id": 533,
        "draft_ids": [],
        "link_ids": [],
        "latest_draft_id": null,
        "payment_request_id": null
      },
      {
        "id": 536,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "created_at": "2017-01-16T13:50:16.801Z",
        "updated_at": "2017-01-16T13:50:16.801Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-536",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": false,
        "campaign_id": 5,
        "supplier_id": 534,
        "draft_ids": [],
        "link_ids": [],
        "latest_draft_id": null,
        "payment_request_id": null
      },
      {
        "id": 542,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "created_at": "2017-01-16T13:50:16.899Z",
        "updated_at": "2017-01-16T13:50:16.899Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-542",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": false,
        "campaign_id": 5,
        "supplier_id": 540,
        "draft_ids": [],
        "link_ids": [],
        "latest_draft_id": null,
        "payment_request_id": null
      },
      {
        "id": 545,
        "supplier_interest": "interested",
        "selectability": "good",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 700.0,
        "price_currency": "EUR",
        "proposed_price": 1000.0,
        "proposed_price_currency": "EUR",
        "comment": "Sujet tr\u00e8s orient\u00e9 RH - ligne \u00e9ditoriale correspondante \u00e0 la cible Top 20%",
        "created_at": "2017-01-16T13:50:16.934Z",
        "updated_at": "2017-01-20T13:58:25.412Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-545",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": false,
        "campaign_id": 5,
        "supplier_id": 543,
        "draft_ids": [],
        "link_ids": [],
        "latest_draft_id": null,
        "payment_request_id": null
      },
      {
        "id": 547,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "created_at": "2017-01-16T13:50:16.958Z",
        "updated_at": "2017-01-16T13:50:16.958Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-547",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": false,
        "campaign_id": 5,
        "supplier_id": 545,
        "draft_ids": [],
        "link_ids": [],
        "latest_draft_id": null,
        "payment_request_id": null
      },
      {
        "id": 546,
        "supplier_interest": "interested",
        "selectability": "good",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": true,
        "price": 450.0,
        "price_currency": "EUR",
        "proposed_price": 450.0,
        "proposed_price_currency": "EUR",
        "comment": "Ax\u00e9 entrepreneuriat - formation - jeunes dipl\u00f4m\u00e9s",
        "created_at": "2017-01-16T13:50:16.946Z",
        "updated_at": "2017-02-07T15:13:08.759Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-546",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": true,
        "campaign_id": 5,
        "supplier_id": 544,
        "draft_ids": [
          25,
          90
        ],
        "link_ids": [
          36,
          37,
          38,
          39,
          40
        ],
        "latest_draft_id": 90,
        "payment_request_id": 15
      },
      {
        "id": 544,
        "supplier_interest": "interested",
        "selectability": "great",
        "client_approved_for_drafting": true,
        "admin_approved_for_drafting": true,
        "price": 60.0,
        "price_currency": "EUR",
        "proposed_price": 60.0,
        "proposed_price_currency": "EUR",
        "comment": "Tr\u00e8s orient\u00e9 B2B - Correspond r\u00e9ellement \u00e0 la cible - Top 20%",
        "created_at": "2017-01-16T13:50:16.920Z",
        "updated_at": "2017-02-08T12:37:40.427Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-544",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": true,
        "campaign_id": 5,
        "supplier_id": 542,
        "draft_ids": [
          34,
          35,
          36,
          37,
          38,
          39,
          87
        ],
        "link_ids": [
          29,
          30,
          31,
          32
        ],
        "latest_draft_id": 87,
        "payment_request_id": 19
      },
      {
        "id": 553,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "created_at": "2017-01-16T13:50:17.037Z",
        "updated_at": "2017-01-16T13:50:17.037Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-553",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": false,
        "campaign_id": 5,
        "supplier_id": 551,
        "draft_ids": [],
        "link_ids": [],
        "latest_draft_id": null,
        "payment_request_id": null
      },
      {
        "id": 554,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 557,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 560,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 561,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 562,
        "supplier_interest": "interested",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": "EUR",
        "proposed_price": 0.0,
        "proposed_price_currency": "EUR",
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 567,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 571,
        "supplier_interest": "not_interested",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": "USD",
        "proposed_price": 0.0,
        "proposed_price_currency": "USD",
        "comment": null,
        "visible_by_client": false,
      },
      {
        "id": 573,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "created_at": "2017-01-16T13:50:17.301Z",
        "updated_at": "2017-01-16T13:50:17.301Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-573",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": false,
        "campaign_id": 5,
        "supplier_id": 571,
        "draft_ids": [],
        "link_ids": [],
        "latest_draft_id": null,
        "payment_request_id": null
      },
      {
        "id": 522,
        "supplier_interest": "interested",
        "selectability": "great",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": true,
        "price": 560.0,
        "price_currency": "EUR",
        "proposed_price": 560.0,
        "proposed_price_currency": "EUR",
        "comment": "Top 1% - B2B - tr\u00e8s bonne visibilit\u00e9",
        "created_at": "2017-01-16T13:50:15.805Z",
        "updated_at": "2017-02-08T10:17:37.452Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-522",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": true,
        "campaign_id": 5,
        "supplier_id": 520,
        "draft_ids": [
          27,
          82
        ],
        "link_ids": [
          25,
          26,
          27,
          28
        ],
        "latest_draft_id": 82,
        "payment_request_id": 18
      },
      {
        "id": 577,
        "supplier_interest": "not_interested",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": "USD",
        "proposed_price": 0.0,
        "proposed_price_currency": "USD",
        "comment": null,
        "created_at": "2017-01-16T13:50:17.349Z",
        "updated_at": "2017-01-20T10:07:38.082Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-577",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": false,
        "campaign_id": 5,
        "supplier_id": 575,
        "draft_ids": [],
        "link_ids": [],
        "latest_draft_id": null,
        "payment_request_id": null
      },
      {
        "id": 578,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "created_at": "2017-01-16T13:50:17.361Z",
        "updated_at": "2017-01-16T13:50:17.361Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-578",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": false,
        "campaign_id": 5,
        "supplier_id": 576,
        "draft_ids": [],
        "link_ids": [],
        "latest_draft_id": null,
        "payment_request_id": null
      },
      {
        "id": 579,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": "USD",
        "proposed_price": 0.0,
        "proposed_price_currency": "USD",
        "comment": null,
        "created_at": "2017-01-16T13:50:17.377Z",
        "updated_at": "2017-01-27T15:46:01.548Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-579",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": false,
        "campaign_id": 5,
        "supplier_id": 577,
        "draft_ids": [],
        "link_ids": [],
        "latest_draft_id": null,
        "payment_request_id": null
      },
      {
        "id": 583,
        "supplier_interest": "unknown_interest",
        "selectability": "unknown_selectability",
        "client_approved_for_drafting": false,
        "admin_approved_for_drafting": false,
        "price": 0.0,
        "price_currency": null,
        "proposed_price": 0.0,
        "proposed_price_currency": null,
        "comment": null,
        "created_at": "2017-01-16T13:50:17.424Z",
        "updated_at": "2017-01-16T13:50:17.424Z",
        "slug": "cci-paris-taxe-d-apprentissage-2017-583",
        "publication_url": null,
        "selling_point": null,
        "visible_by_client": false,
        "campaign_id": 5,
        "supplier_id": 581,
        "draft_ids": [],
        "link_ids": [],
        "latest_draft_id": null,
        "payment_request_id": null
      }
    ];
    //return [
      //{
        //'id': 82236,
        //'firstName': 'Anastasia',
        //'lastName': 'Rosenbaum',
        //'username': 'Hertha6',
        //'email': 'Syble.Smitham@hotmail.com',
        //'website': 'http://halie.org',
        //'city': 'Braunfurt',
        //'phone': '488-641-4354'
      //},
      //{
        //'id': 79437,
        //'firstName': 'Lamont',
        //'lastName': 'Schuster',
        //'username': 'Leora.Nader',
        //'email': 'Destany.Dibbert94@gmail.com',
        //'website': 'http://vella.info',
        //'city': 'MacGyvermouth',
        //'phone': '086.710.7205 x330'
      //},
      //{
        //'id': 48785,
        //'firstName': 'Roberta',
        //'lastName': 'Padberg',
        //'username': 'Ned60',
        //'email': 'Rosamond.Ernser@gmail.com',
        //'website': 'http://clement.info',
        //'city': 'Bergeberg',
        //'phone': '1-140-423-8225'
      //},
      //{
        //'id': 33935,
        //'firstName': 'Alessandro',
        //'lastName': 'Schmitt',
        //'username': 'Brionna51',
        //'email': 'Ewald47@hotmail.com',
        //'website': 'https://filomena.biz',
        //'city': 'West Zena',
        //'phone': '694.678.6993'
      //},
      //{
        //'id': 43007,
        //'firstName': 'Kavon',
        //'lastName': 'Heller',
        //'username': 'Braxton_Pagac14',
        //'email': 'Archibald.Littel36@yahoo.com',
        //'website': 'http://jordyn.biz',
        //'city': 'Jerrystad',
        //'phone': '(086) 503-6677 x2847'
      //},
      //{
        //'id': 3398,
        //'firstName': 'Esteban',
        //'lastName': 'Russel',
        //'username': 'Elinor_Medhurst',
        //'email': 'Sheila_Hackett@yahoo.com',
        //'website': 'https://lane.net',
        //'city': 'West Rey',
        //'phone': '522.706.7649'
      //},
      //{
        //'id': 23568,
        //'firstName': 'Shanny',
        //'lastName': 'Murray',
        //'username': 'Dusty.Ullrich',
        //'email': 'Levi_Goldner@yahoo.com',
        //'website': 'http://jermain.org',
        //'city': 'Paytonview',
        //'phone': '446-412-9437'
      //},
      //{
        //'id': 11463,
        //'firstName': 'Octavia',
        //'lastName': 'Prosacco',
        //'username': 'Ethyl19',
        //'email': 'Wilber.Beer@yahoo.com',
        //'website': 'https://general.net',
        //'city': 'New Nicklaustown',
        //'phone': '424.153.0340 x99467'
      //},
      //{
        //'id': 71610,
        //'firstName': 'Reanna',
        //'lastName': 'Harris',
        //'username': 'Jayne_Treutel',
        //'email': 'Dovie_Keeling@yahoo.com',
        //'website': 'http://christa.com',
        //'city': 'Port Jenniefurt',
        //'phone': '1-582-436-0733'
      //},
      //{
        //'id': 91719,
        //'firstName': 'Julian',
        //'lastName': 'Kuhic',
        //'username': 'Kamryn60',
        //'email': 'Candace.Walsh30@gmail.com',
        //'website': 'http://nola.net',
        //'city': 'Hilpertmouth',
        //'phone': '077.914.7973 x8226'
      //},
      //{
        //'id': 91032,
        //'firstName': 'Bruce',
        //'lastName': 'Wayne',
        //'username': 'batman',
        //'email': 'bruce@waynecorp.com',
        //'website': 'http://savegotham.com',
        //'city': 'Gotham',
        //'phone': '063.916.7970 x8228'
      //},
    //];
  },
});
