import Ember from 'ember';
import faker from 'faker';

export default Ember.Route.extend({
  influencers: [
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'interested',
      'selectability': 'good',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': true,
      'price': '490.0 EUR',
      'proposed_price': '490.0 EUR',
      'comment': 'Cat\u00e9gorie Finance - Education Top 20% ',
      'visible_by_client': true,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'interested',
      'selectability': 'great',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': true,
      'price': '590.0 EUR',
      'proposed_price': '590.0 EUR',
      'proposed_price_currency': 'EUR',
      'comment': 'Tr\u00e8s bonne visibilit\u00e9 - bonne audience Top 5%',
      'visible_by_client': true,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'interested',
      'selectability': 'great',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': true,
      'price': '540.0 EUR',
      'proposed_price': '540.0 EUR',
      'comment': 'Bonne cible B2B - conseils professionnels Top 1%',
      'visible_by_client': true,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'interested',
      'selectability': 'good',
      'client_approved_for_drafting': true,
      'admin_approved_for_drafting': false,
      'price': '300.0 EUR',
      'proposed_price': '300.0 EUR',
      'comment': 'Entrepreneuriat - business Top 20%',
      'visible_by_client': true,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'proposed_price': 0.0,
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'interested',
      'selectability': 'good',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': '200.0 EUR',
      'proposed_price': '200.0 EUR',
      'comment': 'Entrepreneuriat - business Top 20%',
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'interested',
      'selectability': 'great',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': '207.0 EUR',
      'proposed_price': '248.4 EUR',
      'proposed_price_currency': 'EUR',
      'comment': 'Top 5% - blog reconnu en accord avec la cible recherch\u00e9e',
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'proposed_price': 0.0,
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'interested',
      'selectability': 'good',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': '420.0 EUR',
      'proposed_price': '420.0 EUR',
      'comment': 'Power Middle - sujets B2B ',
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'proposed_price': 0.0,
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'proposed_price': 0.0,
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'proposed_price': 0.0,
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'proposed_price': 0.0,
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'interested',
      'selectability': 'good',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': '700.0 EUR',
      'proposed_price': '1000.0 EUR',
      'comment': 'Sujet tr\u00e8s orient\u00e9 RH - ligne \u00e9ditoriale correspondante \u00e0 la cible Top 20%',
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'proposed_price': 0.0,
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'interested',
      'selectability': 'good',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': true,
      'price': '450.0 EUR',
      'proposed_price': '450.0 EUR',
      'comment': 'Ax\u00e9 entrepreneuriat - formation - jeunes dipl\u00f4m\u00e9s',
      'visible_by_client': true,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'interested',
      'selectability': 'great',
      'client_approved_for_drafting': true,
      'admin_approved_for_drafting': true,
      'price': '60.0 EUR',
      'proposed_price': '60.0 EUR',
      'comment': 'Tr\u00e8s orient\u00e9 B2B - Correspond r\u00e9ellement \u00e0 la cible - Top 20%',
      'visible_by_client': true,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'proposed_price': 0.0,
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'proposed_price': 0.0,
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'price_currency': null,
      'proposed_price': 0.0,
      'proposed_price_currency': null,
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'price_currency': null,
      'proposed_price': 0.0,
      'proposed_price_currency': null,
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'price_currency': null,
      'proposed_price': 0.0,
      'proposed_price_currency': null,
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'interested',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'price_currency': 'EUR',
      'proposed_price': 0.0,
      'proposed_price_currency': 'EUR',
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'price_currency': null,
      'proposed_price': 0.0,
      'proposed_price_currency': null,
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'not_interested',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'price_currency': 'USD',
      'proposed_price': 0.0,
      'proposed_price_currency': 'USD',
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'proposed_price': 0.0,
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'interested',
      'selectability': 'great',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': true,
      'price': '560.0 EUR',
      'proposed_price': '560.0 EUR',
      'comment': 'Top 1% - B2B - tr\u00e8s bonne visibilit\u00e9',
      'visible_by_client': true,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'not_interested',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': '0.0 USD',
      'proposed_price': '0.0 USD',
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'proposed_price': 0.0,
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': '0.0 USD',
      'proposed_price': '0.0 USD',
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    },
    {
      'name': faker.name.findName(),
      'media_url': faker.internet.url(),
      'email': faker.internet.email(),
      'supplier_interest': 'unknown_interest',
      'selectability': 'unknown_selectability',
      'client_approved_for_drafting': false,
      'admin_approved_for_drafting': false,
      'price': 0.0,
      'proposed_price': 0.0,
      'comment': null,
      'visible_by_client': false,
      'isSelected': false
    }
  ],

  model() {
    return this.get('influencers').map ( (influencer) => {
      return Ember.Object.create(influencer);
    });
  }
});
