import type OSSAccessPanelComponent from '@upfluence/oss-components/components/o-s-s/access-panel.ts';
import type OSSAlertComponent from '@upfluence/oss-components/components/o-s-s/alert.ts';
import type OSSArrayInputComponent from '@upfluence/oss-components/components/o-s-s/array-input.ts';
import type OSSAttributeBaseComponent from '@upfluence/oss-components/components/o-s-s/attribute/base.ts';
import type OSSAttributeCountryComponent from '@upfluence/oss-components/components/o-s-s/attribute/country.ts';
import type OSSAttributePhoneNumberComponent from '@upfluence/oss-components/components/o-s-s/attribute/phone-number.ts';
import type OSSAttributeRatingComponent from '@upfluence/oss-components/components/o-s-s/attribute/rating.ts';
import type OSSAttributeRemovableTextComponent from '@upfluence/oss-components/components/o-s-s/attribute/removable-text.ts';
import type OSSAttributeRevealableEmailComponent from '@upfluence/oss-components/components/o-s-s/attribute/revealable-email.ts';
import type OSSAttributeTagArrayComponent from '@upfluence/oss-components/components/o-s-s/attribute/tag-array.ts';
import type OSSAttributeTextComponent from '@upfluence/oss-components/components/o-s-s/attribute/text.ts';
import type OSSAttributesPanelComponent from '@upfluence/oss-components/components/o-s-s/attributes-panel.ts';
import type OSSAvatarComponent from '@upfluence/oss-components/components/o-s-s/avatar.ts';
import type OSSBadgeComponent from '@upfluence/oss-components/components/o-s-s/badge.ts';
import type OSSBannerComponent from '@upfluence/oss-components/components/o-s-s/banner.ts';
import type OSSButtonDropdownComponent from '@upfluence/oss-components/components/o-s-s/button-dropdown.ts';
import type OSSButtonComponent from '@upfluence/oss-components/components/o-s-s/button.ts';
import type OSSCheckboxComponent from '@upfluence/oss-components/components/o-s-s/checkbox.ts';
import type OSSChipComponent from '@upfluence/oss-components/components/o-s-s/chip.ts';
import type OSSCodeBlockComponent from '@upfluence/oss-components/components/o-s-s/code-block.ts';
import type OSSContentPanelComponent from '@upfluence/oss-components/components/o-s-s/content-panel.ts';
import type OSSCopyComponent from '@upfluence/oss-components/components/o-s-s/copy.ts';
import type OSSCountrySelectorComponent from '@upfluence/oss-components/components/o-s-s/country-selector.ts';
import type OSSCurrencyInputComponent from '@upfluence/oss-components/components/o-s-s/currency-input.ts';
import type OSSEmailInputComponent from '@upfluence/oss-components/components/o-s-s/email-input.ts';
import type OSSIconComponent from '@upfluence/oss-components/components/o-s-s/icon.ts';
import type OSSIllustrationComponent from '@upfluence/oss-components/components/o-s-s/illustration.ts';
import type OSSInfiniteSelectComponent from '@upfluence/oss-components/components/o-s-s/infinite-select.ts';
import type OSSInputContainerComponent from '@upfluence/oss-components/components/o-s-s/input-container.ts';
import type OSSInputGroupComponent from '@upfluence/oss-components/components/o-s-s/input-group.ts';
import type OSSLayoutSidebarComponent from '@upfluence/oss-components/components/o-s-s/layout/sidebar.ts';
import type OSSLayoutSidebarItemComponent from '@upfluence/oss-components/components/o-s-s/layout/sidebar/item.ts';
import type OSSLinkComponent from '@upfluence/oss-components/components/o-s-s/link.ts';
import type OSSModalDialog from '@upfluence/oss-components/components/o-s-s/modal-dialog.ts';
import type OSSNavTabComponent from '@upfluence/oss-components/components/o-s-s/nav-tab.ts';
import type OSSNumberInputComponent from '@upfluence/oss-components/components/o-s-s/number-input.ts';
import type OSSPanelComponent from '@upfluence/oss-components/components/o-s-s/panel.ts';
import type OSSPanelRowComponent from '@upfluence/oss-components/components/o-s-s/panel/row.ts';
import type OSSPasswordInputComponent from '@upfluence/oss-components/components/o-s-s/password-input.ts';
import type OSSPhoneNumberInputComponent from '@upfluence/oss-components/components/o-s-s/phone-number-input.ts';
import type OSSPowerSelectComponent from '@upfluence/oss-components/components/o-s-s/power-select.ts';
import type OSSProgressBarComponent from '@upfluence/oss-components/components/o-s-s/progress-bar.ts';
import type OSSRadioButtonComponent from '@upfluence/oss-components/components/o-s-s/radio-button.ts';
import type OSSSelectComponent from '@upfluence/oss-components/components/o-s-s/select.ts';
import type OSSSkeletonComponent from '@upfluence/oss-components/components/o-s-s/skeleton.ts';
import type OSSSocialPostBadgeComponent from '@upfluence/oss-components/components/o-s-s/social-post-badge.ts';
import type OSSSplitModalComponent from '@upfluence/oss-components/components/o-s-s/split-modal.ts';
import type OSSStarRatingComponent from '@upfluence/oss-components/components/o-s-s/star-rating.ts';
import type OSSTagComponent from '@upfluence/oss-components/components/o-s-s/tag.ts';
import type OSSTextAreaComponent from '@upfluence/oss-components/components/o-s-s/text-area.ts';
import type OSSTogglableSectionComponent from '@upfluence/oss-components/components/o-s-s/togglable-section.ts';
import type OSSToggleButtonsComponent from '@upfluence/oss-components/components/o-s-s/toggle-buttons.ts';
import type OSSToggleSwitchComponent from '@upfluence/oss-components/components/o-s-s/toggle-switch.ts';
import type OSSUploadAreaComponent from '@upfluence/oss-components/components/o-s-s/upload-area.ts';
import type OSSUploadItemComponent from '@upfluence/oss-components/components/o-s-s/upload-item.ts';
import type OSSUrlInputComponent from '@upfluence/oss-components/components/o-s-s/url-input.ts';
import type FaIconStyleHelper from '@upfluence/oss-components/helpers/fa-icon-style.ts';
import type FaIconValueHelper from '@upfluence/oss-components/helpers/fa-icon-value.ts';
import type RedirectToHelper from '@upfluence/oss-components/helpers/redirect-to.ts';
import type EnableTooltipModifier from '@upfluence/oss-components/modifiers/enable-tooltip.ts';

export default interface AddonRegistry {
  'OSS::AccessPanel': typeof OSSAccessPanelComponent;
  'o-s-s/access-panel': typeof OSSAccessPanelComponent;
  'OSS::Alert': typeof OSSAlertComponent;
  'o-s-s/alert': typeof OSSAlertComponent;
  'OSS::ArrayInput': typeof OSSArrayInputComponent;
  'o-s-s/array-input': typeof OSSArrayInputComponent;
  'OSS::Attribute::Base': typeof OSSAttributeBaseComponent;
  'o-s-s/attribute/base': typeof OSSAttributeBaseComponent;
  'OSS::Attribute::Country': typeof OSSAttributeCountryComponent;
  'o-s-s/attribute/country': typeof OSSAttributeCountryComponent;
  'OSS::Attribute::PhoneNumber': typeof OSSAttributePhoneNumberComponent;
  'o-s-s/attribute/phone-number': typeof OSSAttributePhoneNumberComponent;
  'OSS::Attribute::Rating': typeof OSSAttributeRatingComponent;
  'o-s-s/attribute/rating': typeof OSSAttributeRatingComponent;
  'OSS::Attribute::RemovableText': typeof OSSAttributeRemovableTextComponent;
  'o-s-s/attribute/removable-text': typeof OSSAttributeRemovableTextComponent;
  'OSS::Attribute::RevealableEmail': typeof OSSAttributeRevealableEmailComponent;
  'o-s-s/attribute/revealable-email': typeof OSSAttributeRevealableEmailComponent;
  'OSS::Attribute::TagArray': typeof OSSAttributeTagArrayComponent;
  'o-s-s/attribute/tag-array': typeof OSSAttributeTagArrayComponent;
  'OSS::Attribute::Text': typeof OSSAttributeTextComponent;
  'o-s-s/attribute/text': typeof OSSAttributeTextComponent;
  'OSS::AttributesPanel': typeof OSSAttributesPanelComponent;
  'o-s-s/attributes-panel': typeof OSSAttributesPanelComponent;
  'OSS::Avatar': typeof OSSAvatarComponent;
  'o-s-s/avatar': typeof OSSAvatarComponent;
  'OSS::Badge': typeof OSSBadgeComponent;
  'o-s-s/badge': typeof OSSBadgeComponent;
  'OSS::Banner': typeof OSSBannerComponent;
  'o-s-s/banner': typeof OSSBannerComponent;
  'OSS::ButtonDropdown': typeof OSSButtonDropdownComponent;
  'o-s-s/button-dropdown': typeof OSSButtonDropdownComponent;
  'OSS::Button': typeof OSSButtonComponent;
  'o-s-s/button': typeof OSSButtonComponent;
  'OSS::Checkbox': typeof OSSCheckboxComponent;
  'o-s-s/checkbox': typeof OSSCheckboxComponent;
  'OSS::Chip': typeof OSSChipComponent;
  'o-s-s/chip': typeof OSSChipComponent;
  'OSS::CodeBlock': typeof OSSCodeBlockComponent;
  'o-s-s/code-block': typeof OSSCodeBlockComponent;
  'OSS::ContentPanel': typeof OSSContentPanelComponent;
  'o-s-s/content-panel': typeof OSSContentPanelComponent;
  'OSS::Copy': typeof OSSCopyComponent;
  'o-s-s/copy': typeof OSSCopyComponent;
  'OSS::CountrySelector': typeof OSSCountrySelectorComponent;
  'o-s-s/country-selector': typeof OSSCountrySelectorComponent;
  'OSS::CurrencyInput': typeof OSSCurrencyInputComponent;
  'o-s-s/currency-input': typeof OSSCurrencyInputComponent;
  'OSS::EmailInput': typeof OSSEmailInputComponent;
  'o-s-s/email-input': typeof OSSEmailInputComponent;
  'OSS::Icon': typeof OSSIconComponent;
  'o-s-s/icon': typeof OSSIconComponent;
  'OSS::Illustration': typeof OSSIllustrationComponent;
  'o-s-s/illustration': typeof OSSIllustrationComponent;
  'OSS::InfiniteSelect': typeof OSSInfiniteSelectComponent;
  'o-s-s/infinite-select': typeof OSSInfiniteSelectComponent;
  'OSS::InputContainer': typeof OSSInputContainerComponent;
  'o-s-s/input-container': typeof OSSInputContainerComponent;
  'OSS::InputGroup': typeof OSSInputGroupComponent;
  'o-s-s/input-group': typeof OSSInputGroupComponent;
  'OSS::Layout::Sidebar': typeof OSSLayoutSidebarComponent;
  'o-s-s/layout/sidebar': typeof OSSLayoutSidebarComponent;
  'OSS::Layout::Sidebar::Item': typeof OSSLayoutSidebarItemComponent;
  'o-s-s/layout/sidebar/item': typeof OSSLayoutSidebarItemComponent;
  'OSS::Link': typeof OSSLinkComponent;
  'o-s-s/link': typeof OSSLinkComponent;
  'OSS::ModalDialog': typeof OSSModalDialog;
  'o-s-s/modal-dialog': typeof OSSModalDialog;
  'OSS::NavTab': typeof OSSNavTabComponent;
  'o-s-s/nav-tab': typeof OSSNavTabComponent;
  'OSS::NumberInput': typeof OSSNumberInputComponent;
  'o-s-s/number-input': typeof OSSNumberInputComponent;
  'OSS::Panel': typeof OSSPanelComponent;
  'o-s-s/panel': typeof OSSPanelComponent;
  'OSS::Panel::Row': typeof OSSPanelRowComponent;
  'o-s-s/panel/row': typeof OSSPanelRowComponent;
  'OSS::PasswordInput': typeof OSSPasswordInputComponent;
  'o-s-s/password-input': typeof OSSPasswordInputComponent;
  'OSS::PhoneNumberInput': typeof OSSPhoneNumberInputComponent;
  'o-s-s/phone-number-input': typeof OSSPhoneNumberInputComponent;
  'OSS::PowerSelect': typeof OSSPowerSelectComponent;
  'o-s-s/power-select': typeof OSSPowerSelectComponent;
  'OSS::ProgressBar': typeof OSSProgressBarComponent;
  'o-s-s/progress-bar': typeof OSSProgressBarComponent;
  'OSS::RadioButton': typeof OSSRadioButtonComponent;
  'o-s-s/radio-button': typeof OSSRadioButtonComponent;
  'OSS::Select': typeof OSSSelectComponent;
  'o-s-s/select': typeof OSSSelectComponent;
  'OSS::Skeleton': typeof OSSSkeletonComponent;
  'o-s-s/skeleton': typeof OSSSkeletonComponent;
  'OSS::SocialPostBadge': typeof OSSSocialPostBadgeComponent;
  'o-s-s/social-post-badge': typeof OSSSocialPostBadgeComponent;
  'OSS::SplitModal': typeof OSSSplitModalComponent;
  'o-s-s/split-modal': typeof OSSSplitModalComponent;
  'OSS::StarRating': typeof OSSStarRatingComponent;
  'o-s-s/star-rating': typeof OSSStarRatingComponent;
  'OSS::Tag': typeof OSSTagComponent;
  'o-s-s/tag': typeof OSSTagComponent;
  'OSS::TextArea': typeof OSSTextAreaComponent;
  'o-s-s/text-area': typeof OSSTextAreaComponent;
  'OSS::TogglableSection': typeof OSSTogglableSectionComponent;
  'o-s-s/togglable-section': typeof OSSTogglableSectionComponent;
  'OSS::ToggleButtons': typeof OSSToggleButtonsComponent;
  'o-s-s/toggle-buttons': typeof OSSToggleButtonsComponent;
  'OSS::ToggleSwitch': typeof OSSToggleSwitchComponent;
  'OSS::UploadArea': typeof OSSUploadAreaComponent;
  'o-s-s/upload-area': typeof OSSUploadAreaComponent;
  'OSS::UploadItem': typeof OSSUploadItemComponent;
  'o-s-s/upload-item': typeof OSSUploadItemComponent;
  'OSS::UrlInput': typeof OSSUrlInputComponent;
  'o-s-s/url-input': typeof OSSUrlInputComponent;
  'fa-icon-style': typeof FaIconStyleHelper;
  'fa-icon-value': typeof FaIconValueHelper;
  'redirect-to': typeof RedirectToHelper;
  'enable-tooltip': typeof EnableTooltipModifier;
}
